env:
  global:
    - CC_TEST_REPORTER_ID=fb0140a9e97adaa5139ab8f5a3c4c4c2b09ef35f56f847bdfe690cadaef6be23
sudo: false
language: ruby
cache: bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
matrix:
  include:
  - rvm: ruby-head
    gemfile: Gemfile
  - rvm: 2.6
    gemfile: Gemfile
  - rvm: 2.5
    gemfile: Gemfile
  - rvm: 2.4
    gemfile: Gemfile
  - rvm: 2.3
    gemfile: Gemfile
  - rvm: 2.2
    gemfile: Gemfile
  - rvm: 2.1
    gemfile: Gemfile
  - rvm: 2.0
    gemfile: Gemfile
script: bundle exec rspec -fd
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
